### ISSUE TITLE
Copy Button

### ISSUE THREAD

**Issue by smaragdus** [Lewiscowles1986/save-tabs-as-markdown-ff-chrome-poc#3]
A simple enhancement for this extension would be a new button:

- **Copy**

mock-up:

![Save Tab URLs to Markdown 0 1 2 - 2020-03-29 - 006](https://user-images.githubusercontent.com/9025757/77839583-b5ed3700-7186-11ea-98be-12f8f7616d2e.png)

which copies the URL list without saving it to file. If such a button is added copying the URL list would be faster as the user would not need to click in the text box and execute 'CTRL+A' and 'CTRL+C' commands. Quite often I need just to copy URLs in Markdown format and paste them in Markdown editor in stead of saving them to file. I suppose that other users might find such 'Copy' button useful too. If such 'Copy' button is implemented the buttons order might be the following:

- **Copy**
- **Save**

I think that just `Save` would be better than `Save as...` because it would be shorter, it would match the overall style, and because it would be more accurate as the file is saved automatically, without providing and option for 'Save as...'.

**Comment by Lewiscowles1986** [comment]
I know all browsers supported can handle this, but I doubt I'll add it myself because as you've mentioned you can manually select-all, copy and paste into your editor of choice.

This might be a case for forking the plugin; doing the work and showing over a period of time it's not going to take up lots of time to maintain everyone's preferences, which is why I have it saving files.

**Comment by Lewiscowles1986** [comment]
`Save as...` -> `Save` should also be a separate issue
